version: '3.9'
services:
  db:
    image: mysql:8
    container_name: express-ddd-database # phpMyAdminサービスのPMA_HOSTSに設定する
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USER_PASS}
      TZ: 'Asia/Tokyo'
      LC_ALL: 'ja_JP.UTF-8'
      LANG: "ja_JP.UTF-8"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    env_file:
      - .env
    volumes:
      - ./container/db/data:/var/lib/mysql
      - ./container/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - ${PORT}:3306
    expose:
      - ${PORT}

  express:
    image: express-ddd-prod-image
    container_name: express-ddd-prod-container
    build:
      context: .
      dockerfile: ./container/nodejs/Dockerfile.Prod
#    volumes:
#      - ./express:/app
    ports:
      - "8080:8080"
#    command: yarn start
    tty: true

    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ".env"
    depends_on:
      db:
        condition: service_healthy
