version: '3.9'
services:
  db:
    image: postgres:latest
    volumes:
      - ./container/db/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${USER_PASS}
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${USERNAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USERNAME} -d ${DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - .env
    ports:
      - "5432:5432"

  express:
    image: express-ddd-sample-image
    container_name: express-ddd-sample-container
    build:
      context: .
      dockerfile: ./container/nodejs/Dockerfile
    volumes:
      - ./express:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    command: npm run start
    tty: true

    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ".env"
    depends_on:
      db:
        condition: service_healthy
