### GET request to task list
GET http://0.0.0.0:8080/api/v1/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJ1c2VySWQiOjEsImlhdCI6MTcyNTg1MDc3MywiZXhwIjoxNzI1ODU0MzczfQ.lk-uF7b4eYjjy6xD_sOdKziA9ZcgGULq38LcUhVv0Rc


### POST Taskの登録
POST http://0.0.0.0:8080/api/v1/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJ1c2VySWQiOjEsImlhdCI6MTcyNTg1MDc3MywiZXhwIjoxNzI1ODU0MzczfQ.lk-uF7b4eYjjy6xD_sOdKziA9ZcgGULq38LcUhVv0Rc

{
  "deadline": "2024-08-15T17:00",
  "isBookMark": 0,
  "isDeleted": false,
  "status": 0,
  "taskDeadline": 1723708800000,
  "text": "テスト",
  "title": "テスト",
  "url": "https://sample.co.jp/",
  "isMyTask": true,
  "isTimeIncluded": true
}

### PATCH Taskの更新
PATCH http://0.0.0.0:8080/api/v1/tasks/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJ1c2VySWQiOjEsImlhdCI6MTcyNTg1MDc3MywiZXhwIjoxNzI1ODU0MzczfQ.lk-uF7b4eYjjy6xD_sOdKziA9ZcgGULq38LcUhVv0Rc

{
  "deadline": "2024-08-15T17:00",
  "isBookMark": 0,
  "isDeleted": false,
  "status": 0,
  "taskDeadline": 1723708800000,
  "text": "テスト3",
  "title": "テスト2",
  "url": "https://sample.co.jp/",
  "isMyTask": false,
  "isTimeIncluded": true
}


### GET Taskの取得
GET http://0.0.0.0:8080/api/v1/tasks/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJ1c2VySWQiOjEsImlhdCI6MTcyNTg1MDc3MywiZXhwIjoxNzI1ODU0MzczfQ.lk-uF7b4eYjjy6xD_sOdKziA9ZcgGULq38LcUhVv0Rc
