### GET request to signup
GET http://localhost:8000/api/v1/users
Content-Type: application/json

### POST request to 登録
POST http://localhost:8000/api/v1/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "testj3%Ytv"
}


### POST request to ログイン
POST http://localhost:8000/api/v1/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "testj3%Ytv"
}